<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resume_template" nsURI="resume_template" nsPrefix="resume_template">
  <eClassifiers xsi:type="ecore:EClass" name="ResumeTemplate">
    <eAnnotations source="gmf"/>
    <eAnnotations source="gmf.diagram"/>
    <eAnnotations source="exeed">
      <details key="label" value="return 'ResumeTemplate';"/>
      <details key="classIcon" value="resource"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folderName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Resume Templates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Resume Template"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFont" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Arial"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="11"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTablePadding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="themeColors" upperBound="-1"
        eType="#//ThemeColor" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThemeColor">
    <eAnnotations source="gmf.node">
      <details key="label" value="colorCode"/>
      <details key="label.pattern" value="Color code: {0}"/>
      <details key="figure" value="ellipse"/>
      <details key="size" value="150,30"/>
    </eAnnotations>
    <eAnnotations source="exeed">
      <details key="label" value="return 'Color code: ' + self.colorCode;"/>
      <details key="classIcon" value="group"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="themeColor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colorCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="#FFFFFF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutoGenerated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="font" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUppercase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isItalic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hAlignment" eType="#//HAlignment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//ThemeColor">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HAlignment">
    <eLiterals name="LEFT"/>
    <eLiterals name="CENTER" value="1"/>
    <eLiterals name="RIGHT" value="2"/>
    <eLiterals name="JUSTIFY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//TextElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="isAutoGenerated,text,length"/>
      <details key="label.pattern" value="Paragraph {0,choice,0#text: {1}|1#length: {2}}"/>
      <details key="figure" value="polygon"/>
      <details key="polygon.x" value="0 90 100 90 90 100 100 0"/>
      <details key="polygon.y" value="0 0 10 10 0 10 40 40"/>
    </eAnnotations>
    <eAnnotations source="exeed">
      <details key="label" value="&#xD;&#xA;&#x9;&#x9;var label : String;&#xD;&#xA;&#x9;&#x9;label = 'Paragraph ';&#xD;&#xA;&#x9;&#x9;if(self.isAutoGenerated) {&#xD;&#xA;&#x9;&#x9;&#x9;label = label + 'length: ' + self.length;&#xD;&#xA;&#x9;&#x9;} else {&#xD;&#xA;&#x9;&#x9;&#x9;label = label + 'text: ' + self.text;&#x9;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;}&#xD;&#xA;&#x9;&#x9;return label;&#xD;&#xA;&#x9;"/>
      <details key="classIcon" value="text"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//TextElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="numItems"/>
      <details key="label.pattern" value="List numItems: {0}"/>
      <details key="figure" value="polygon"/>
      <details key="polygon.x" value="0 90 100 90 90 100 100 0 0 3 6 3 0 0 3 6 3 0 0 3 6 3 0"/>
      <details key="polygon.y" value="0 0 10 10 0 10 40 40 35 32 35 38 35 25 22 25 28 25 15 12 15 18 15"/>
    </eAnnotations>
    <eAnnotations source="exeed">
      <details key="label" value="return 'List numItems: ' + self.numItems;"/>
      <details key="classIcon" value="text"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="glyphType" eType="#//GlyphType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GlyphType">
    <eLiterals name="BULLET"/>
    <eLiterals name="HOLLOW_BULLET" value="1"/>
    <eLiterals name="SQUARE_BULLET" value="2"/>
    <eLiterals name="NUMBER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="label" value="numRows,numCols"/>
      <details key="label.pattern" value="Table size: {0}x{1}"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eAnnotations source="exeed">
      <details key="label" value="return 'Table size: ' + self.numRows + 'x' + self.numCols;"/>
      <details key="classIcon" value="table"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numRows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCols" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widthPropCols" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="padding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bgColor" eType="#//ThemeColor">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eAnnotations source="gmf.node">
      <details key="label" value="rowIdx,colIdx"/>
      <details key="label.pattern" value="Cell idx: ({0},{1})"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eAnnotations source="exeed">
      <details key="label" value="return 'Cell idx: (' + self.rowIdx + ',' + self.colIdx + ')';"/>
      <details key="classIcon" value="column"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textElements" upperBound="-1"
        eType="#//TextElement" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HorizontalLine" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="label" value="size"/>
      <details key="label.pattern" value="HorizontalLine size: {0}"/>
      <details key="figure" value="polygon"/>
      <details key="size" value="700,5"/>
      <details key="polygon.x" value="0 500"/>
      <details key="polygon.y" value="0 0"/>
    </eAnnotations>
    <eAnnotations source="exeed">
      <details key="label" value="return 'HorizontalLine size: ' + self.size;"/>
      <details key="classIcon" value="transition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="5"/>
  </eClassifiers>
</ecore:EPackage>
