/**
 */
package resume_template;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paragraph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link resume_template.Paragraph#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see resume_template.Resume_templatePackage#getParagraph()
 * @model annotation="gmf.node label='isAutoGenerated,text,length' label.pattern='Paragraph {0,choice,0#text: {1}|1#length: {2}}' figure='polygon' polygon.x='0 90 100 90 90 100 100 0' polygon.y='0 0 10 10 0 10 40 40'"
 *        annotation="exeed label='\r\n\t\tvar label : String;\r\n\t\tlabel = \'Paragraph \';\r\n\t\tif(self.isAutoGenerated) {\r\n\t\t\tlabel = label + \'length: \' + self.length;\r\n\t\t} else {\r\n\t\t\tlabel = label + \'text: \' + self.text;\t\t\t\r\n\t\t}\r\n\t\treturn label;\r\n\t' classIcon='text'"
 * @generated
 */
public interface Paragraph extends TextElement {
	/**
	 * Returns the value of the '<em><b>Length</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Length</em>' attribute.
	 * @see #setLength(int)
	 * @see resume_template.Resume_templatePackage#getParagraph_Length()
	 * @model
	 * @generated
	 */
	int getLength();

	/**
	 * Sets the value of the '{@link resume_template.Paragraph#getLength <em>Length</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Length</em>' attribute.
	 * @see #getLength()
	 * @generated
	 */
	void setLength(int value);

} // Paragraph
